// <auto-generated />
namespace MoviesDatabase.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makinguser_moviesratingandisWatchedcolumsnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makinguser_moviesratingandisWatchedcolumsnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051816335_making user_movies rating and isWatched colums nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
